# Generated by Django 5.2.3 on 2025-07-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Author",
            new_name="Article",
        ),
    ]
