# Generated by Django 5.2.3 on 2025-07-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0005_tag_article_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="pub_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
