# Generated by Django 5.2.3 on 2025-07-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField()),
                ("username", models.CharField(max_length=100)),
                ("data_joined", models.DateTimeField(auto_now_add=True)),
                ("email", models.EmailField(max_length=254)),
                ("visit_count", models.IntegerField()),
                ("profile", models.TextField()),
                ("website", models.URLField()),
            ],
        ),
    ]
