# Generated by Django 5.2.3 on 2025-07-20 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_tga"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="Tga",
        ),
    ]
