# Generated by Django 5.2.3 on 2025-07-20 03:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_tag_delete_tga"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="create_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
