# Generated by Django 5.2.3 on 2025-07-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0006_alter_tag_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ("-pub_time", "name")},
        ),
        migrations.AlterModelTable(
            name="book",
            table="book",
        ),
    ]
