# Generated by Django 5.2.3 on 2025-07-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0007_alter_book_options_alter_book_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="book",
            table="book_table",
        ),
    ]
